namespace SecureHomeSystem.Configuration;

/// <summary>
/// Defines retention limits for service log files generated by
/// <see cref="Services.ContainerLogCollector" />. Thresholds are optional—set
/// values to zero or negative to disable a specific limit.
/// </summary>
public sealed class LogRotationOptions
{
    /// <summary>
    /// Maximum size (in bytes) for the active log file before it is rotated.
    /// </summary>
    public long MaxFileSizeBytes { get; set; } = 10 * 1024 * 1024;

    /// <summary>
    /// Maximum age (in days) for the active log file before it is rotated.
    /// </summary>
    public int MaxFileAgeDays { get; set; } = 7;

    /// <summary>
    /// Maximum number of rotated archives to keep per service. Newer files are
    /// retained first. Set to zero or negative to disable pruning by count.
    /// </summary>
    public int MaxArchiveFiles { get; set; } = 5;
}
